import { main as dayOneMain } from "./Day-1";
import { main as dayTwoMain } from "./Day-2";
import { main as dayThreeMain } from "./Day-3";
import { main as dayFourMain } from "./Day-4";
import { main as dayFiveMain } from "./Day-5";
import { main as daySixMain } from "./Day-6";
import { main as daySevenMain } from "./Day-7";
import { main as dayEightMain } from "./Day-8";
import { main as dayNineMain } from "./Day-9";
import { main as dayTenMain } from "./Day-10";
import { main as dayElevenMain } from "./Day-11";
import { main as dayTwelveMain } from "./Day-12";
import { main as dayThirteenMain } from "./Day-13";
import { main as dayFourteenMain } from "./Day-14";
import { main as dayFifteenMain } from "./Day-15";
import { main as daySixteenMain } from "./Day-16";
import { main as daySeventeenMain } from "./Day-17";
import { main as dayEighteenMain } from "./Day-18";
import { main as dayNineteenMain } from "./Day-19";
import { main as dayTwentyMain } from "./Day-20";
import { main as dayTwentyOneMain } from "./Day-21";
import { main as dayTwentyTwoMain } from "./Day-22";
import { main as dayTwentyThreeMain } from "./Day-23";
import { main as dayTwentyFourMain } from "./Day-24";
import { main as dayTwentyFiveMain } from "./Day-25";


// dayOneMain();
// dayTwoMain();
// dayThreeMain();
// dayFourMain();
// dayFiveMain();
// daySixMain();
// daySevenMain();
// dayEightMain();
// dayNineMain();
// dayTenMain();
dayElevenMain();
// dayTwelveMain();
// dayThirteenMain();
// dayFourteenMain();
// dayFifteenMain();
// daySixteenMain();
// daySeventeenMain();
// dayEighteenMain();
// dayNineteenMain();
// dayTwentyMain();
// dayTwentyOneMain();
// dayTwentyTwoMain();
// dayTwentyThreeMain();
// dayTwentyFourMain();
// dayTwentyFiveMain();